# Generated by Django 3.2.6 on 2021-10-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
