# Generated by Django 3.2.6 on 2021-10-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_venues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venues',
            new_name='Venue',
        ),
    ]
